on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  document:
    name: Markdown Bundler
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: create markdown bundle
        run: |
          cd main
          npx bundle-md projects --output ../auto_md_bundle
          cd ../
      - name: checkout wiki
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
      - name: copy over files
        run: |
          rm -rf wiki/bundle-md/
          mkdir -p wiki/bundle-md/images
          cp auto_md_bundle/bundle.md wiki/bundle/Folder-Architecture.md
          cp auto_md_bundle/images/* wiki/bundle/images/
      - name: commit changes
        run: |
          cd wiki
          git config --global user.name bundle-md
          git config --global user.email bundle-md@users.noreply.github.com
          git add bundle/*
          git commit -m "Update auto-generated folder architecture file"
          git push
